# Generated by Django 5.2.4 on 2025-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='hero/', verbose_name='Arka Plan Görseli')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Alt Başlık')),
                ('button_text', models.CharField(max_length=50, verbose_name='Buton Yazısı')),
                ('button_link', models.URLField(verbose_name='Buton Linki')),
            ],
        ),
    ]
