# Generated by Django 5.2.4 on 2025-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(max_length=200, verbose_name='Buton Linki'),
        ),
    ]
