# Generated by Django 5.2.4 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='İçindekiler'),
        ),
    ]
