# Generated by Django 5.2.4 on 2025-07-21 13:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cafesection_cafeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('salon_fee', models.BooleanField(default=False)),
                ('musician', models.BooleanField(default=False)),
                ('photographer', models.BooleanField(default=False)),
                ('qr_sharing', models.BooleanField(default=False)),
                ('kina_concept', models.BooleanField(default=False)),
                ('wedding_concept', models.BooleanField(default=False)),
                ('snack_options', models.CharField(blank=True, max_length=255)),
                ('meal_options', models.CharField(blank=True, max_length=255)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('car_decoration', models.BooleanField(default=False)),
                ('vip_car_service', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cafeitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
