# Generated by Django 5.2.4 on 2025-07-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_organizationservice_weddingorganizationrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationService',
        ),
        migrations.DeleteModel(
            name='WeddingOrganizationRequest',
        ),
    ]
