# Generated by Django 5.2.4 on 2025-07-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_weddingorganization_alter_cafeitem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet_adi', models.CharField(max_length=100)),
                ('birim_fiyati', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
