# Generated by Django 5.2.4 on 2025-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_organizationservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('dugun', 'Düğün'), ('nisan', 'Nişan'), ('kına', 'Kına'), ('dogumgunu', 'Doğum Günü')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('per_person', models.BooleanField(default=False)),
            ],
        ),
    ]
