# Generated by Django 5.2.4 on 2025-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_organizationservicepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('salon', 'Salon Ücreti'), ('muzisyen', 'Müzisyen / Şantör'), ('fotografci', 'Fotoğrafçı'), ('qr', 'QR Kod Fotoğraf Paylaşımı'), ('kina', 'Kına Konsepti'), ('dugun', 'Düğün Konsepti'), ('araba', 'Araba Süsleme'), ('vip_arac', 'VIP Araç Hizmeti'), ('yemek_et', 'Yemek (Et)'), ('yemek_tavuk', 'Yemek (Tavuk)'), ('yemek_vegan', 'Yemek (Vegan)'), ('ikram_yas_pasta', 'Yaş Pasta'), ('ikram_kuru_pasta', 'Kuru Pasta'), ('ikram_cerez', 'Çerez'), ('ikram_mesrubat', 'Meşrubat'), ('ikram_cay', 'Çay')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_per_person', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeddingOrganizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('selected_services', models.JSONField()),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizationServicePricing',
        ),
        migrations.DeleteModel(
            name='WeddingOrganization',
        ),
    ]
