# Generated by Django 5.2.4 on 2025-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_organizationservice_weddingorganizationrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationservice',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='weddingorganizationrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weddingorganizationrequest',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='weddingorganizationrequest',
            name='selected_services',
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Sitede gösterilsin mi?'),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hizmetin birim fiyatı', max_digits=10),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='customer_name',
            field=models.CharField(default='', max_length=100, verbose_name='Müşteri Adı'),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='customer_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='event_date',
            field=models.DateField(default='', verbose_name='Etkinlik Tarihi'),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Müşteri Notları'),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='selected_services_summary',
            field=models.JSONField(default='', verbose_name='Seçilen Hizmetler Özeti'),
        ),
        migrations.AddField(
            model_name='weddingorganizationrequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Fiyat'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='is_per_person',
            field=models.BooleanField(default=False, help_text='Fiyat kişi başı mı hesaplanacak?'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='key',
            field=models.CharField(help_text="Kod içinde kullanılacak anahtar (örn: 'salon_ucreti')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='name',
            field=models.CharField(help_text="Müşteriye gösterilecek isim (örn: 'Salon Ücreti')", max_length=255),
        ),
        migrations.AlterField(
            model_name='weddingorganizationrequest',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Davetli Sayısı'),
        ),
    ]
