# Generated by Django 5.2.4 on 2025-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_organizationservice_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingorganizationrequest',
            name='selected_services_summary',
            field=models.JSONField(default=dict, verbose_name='Seçilen Hizmetler Özeti'),
        ),
    ]
