# Generated by Django 5.2.4 on 2025-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_serviceoption_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='organization_type',
            field=models.CharField(choices=[('salon', 'Salon'), ('musician', 'Musician'), ('photographer', 'Photographer'), ('concept', 'Concept'), ('catering', 'Catering'), ('vip_car', 'VIP Car')], max_length=20),
        ),
    ]
