# Generated by Django 5.2.4 on 2025-07-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_serviceoption_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoption',
            name='category',
            field=models.CharField(choices=[('musician', 'Müzisyen'), ('vip_car', 'Araç Süsleme'), ('food', 'Yemek'), ('cake', 'Pasta')], default='musician', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='organization_type',
            field=models.CharField(choices=[('dugun', 'Düğün'), ('nisan', 'Nişan'), ('kina', 'Kına')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
