# Generated by Django 5.2.4 on 2025-07-22 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_weddingorganizationrequest_selected_services_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingorganizationrequest',
            name='event_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Etkinlik Tarihi'),
        ),
    ]
