# Generated by Django 5.2.4 on 2025-07-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_weddingorganizationrequest_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingorganizationrequest',
            name='event_date',
            field=models.DateField(default='2024-01-01', verbose_name='Etkinlik Tarihi'),
        ),
    ]
