# Generated by Django 5.2.4 on 2025-07-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_weddingorganizationrequest_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationService',
        ),
        migrations.DeleteModel(
            name='WeddingOrganizationRequest',
        ),
    ]
