# Generated by Django 5.2.4 on 2025-07-23 10:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_organizationtype_servicecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexgallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
